project:
  type: website

website:
  title: "Home"
  open-graph: true
  search: false
  page-footer: "Made with ❤️ and Quarto"
  navbar:
    background: '#FAFBFD'
    right:
      - text: About
        href: about/index.qmd
      - text: Projects
        href: projects/index.qmd
      - text: Learning Lab
        href: lab/index.qmd
      - text: Talks
        href: talks/index.qmd

format:
  html:
    theme: [cosmo, styles.scss]
